apiVersion: litmuschaos.io/v1alpha1
kind: ChaosSchedule
metadata:
  name: pod-delete-kafka
spec:
  schedule:
    repeat:
      properties:
         #format should be like "10m" or "2h" accordingly for minutes or hours
        minChaosInterval: "2m"  
  engineTemplateSpec:
    engineState: active
    appinfo:
      appns: 'kafka-cluster'
      applabel: 'app.kubernetes.io/name=kafka'
      appkind: 'statefulset'
    annotationCheck: 'false'
    chaosServiceAccount: pod-delete-sa
    monitoring: false
    jobCleanUpPolicy: 'delete'
    experiments:
      - name: pod-delete
        spec:
          components:
            env:
              # set chaos duration (in sec) as desired
              - name: TOTAL_CHAOS_DURATION
                value: '30'

              # set chaos interval (in sec) as desired
              - name: CHAOS_INTERVAL
                value: '10'

              # pod failures without '--force' & default terminationGracePeriodSeconds
              - name: FORCE
                value: 'false'