apiVersion: litmuschaos.io/v1alpha1
kind: ChaosSchedule
metadata:
  name: pod-delete
  namespace: litmus
spec:
  schedule:
    repeat:
      properties:
        #format should be like "10m" or "2h" accordingly for minutes and hours
        minChaosInterval: "2m"   
      workDays:
        includedDays: "Mon,Tue,Wed,Sat,Sun"
      workHours:
        # format should be <starting-hour-number>-<ending-hour-number>(inclusive)
        includedHours: 0-12
  #update to halt to pause
  scheduleState: active
  engineTemplateSpec:
    appinfo:
      appns: '<namespace>'
      applabel: '<pod-label>'
      appkind: '<deployment-type>'
    annotationCheck: 'false'
    auxiliaryAppInfo: ''
    chaosServiceAccount: pod-delete-sa
    monitoring: false
    jobCleanUpPolicy: '<cleanup>'
    experiments:
      - name: pod-delete
        spec:
          components:
            env:
              # set chaos duration (in sec) as desired
              - name: TOTAL_CHAOS_DURATION
                value: '<chaos-duration>'

              # set chaos interval (in sec) as desired
              - name: CHAOS_INTERVAL
                value: '<chaos-interval>'

              # pod failures without '--force' & default terminationGracePeriodSeconds
              - name: FORCE
                value: '<force-delete>'